### PR TITLE
Create swordlore2.py

### PR DESCRIPTION
**Pull request by Wheatwizard**
Sorry I can't seem to make a proper pull request but I've done about half the required merges on swordlore.py.

### CODE REVIEW

**Comment by 1000000000** [comment]
what is left unmerged?

**Comment by Wheatwizard** [comment]
Everything from marks corrections onwards

**Comment by Wheatwizard** [comment]
I've done marks merges too though if you want me to update this

**Comment by 1000000000** [comment]
Oh, I just finished them myself. Wasn't quite sure how to continue with yours so I redid my merge.

**Pull request closed without merging**
